version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/meusite:$IMAGE_TAG .
      - docker tag <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/meusite:$IMAGE_TAG <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/meusite:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/meusite:$IMAGE_TAG
      - docker push <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/meusite:latest
      - echo Writing image definitions file...
      - printf '[{"name":"meusite-container","imageUri":"%s"}]' <524664341235>.dkr.ecr.us-east-1.amazonaws.com/meusite:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
